#!/command/with-contenv bash
# entrypoint-local.sh — Fork entrypoint.
# Applies container-fixes (dynamically generated by Hermes) BEFORE
# /run.sh runs. Since /run.sh hasn't started yet, it's safe to patch it.
#
# container-fixes.py is NOT in the repo — Hermes generates it at
# /config/fixes/container-fixes.py from apply-fixes.py.
#
# The apply_fixes config option controls whether fixes run.
# Set apply_fixes=false to skip container-fixes and boot clean.
set -euo pipefail

APPLY_FIXES=$(bashio::config 'apply_fixes')
CONTAINER_FIXES="/config/fixes/container-fixes.py"

if [ "${APPLY_FIXES}" = "true" ] && [ -f "$CONTAINER_FIXES" ]; then
    echo "[entrypoint] applying container-fixes (includes /run.sh)..."
    python3 "$CONTAINER_FIXES" --with-runsh 2>&1 | sed 's/^/[container-fixes] /' || true
fi

exec /run.sh "$@"
