#!/command/with-contenv bash
# entrypoint-local.sh — Fork entrypoint.
# Applies container-fixes (dynamically generated by Hermes) BEFORE
# /run.sh runs. Since /run.sh hasn't started yet, it's safe to patch it.
#
# container-fixes.py is NOT in the repo — Hermes generates it at
# /config/fixes/container-fixes.py from apply-fixes.py.
#
# The apply_fixes config option controls whether fixes run.
# Set apply_fixes=false to skip container-fixes and boot clean.
set -euo pipefail

OPTIONS_FILE="/data/options.json"
# Default true; only an explicit `false` in the addon options disables fixes.
APPLY_FIXES=$(jq -r 'if .apply_fixes == false then "false" else "true" end' "$OPTIONS_FILE")
CONTAINER_FIXES="/config/fixes/container-fixes.py"

if [ "${APPLY_FIXES}" != "true" ]; then
    echo "[entrypoint] container-fixes DISABLED by addon option (apply_fixes=false) — booting stock /run.sh"
elif [ ! -f "$CONTAINER_FIXES" ]; then
    echo "[entrypoint] container-fixes not generated yet (Hermes will create them on first boot) — nothing to patch"
else
    echo "[entrypoint] applying container-fixes to the image before /run.sh starts..."
    python3 "$CONTAINER_FIXES" --with-runsh 2>&1 | sed 's/^/[container-fixes] /' || true
fi

exec /run.sh "$@"
